# WIP
version: '3.8'

services:
  service_1:
    image: node:20
    hostname: service_1
    container_name : api-gateway_container
    env_file:
      - .env.docker.local
    ports:
      - 8000:8000
    volumes: 
      - "dist/api-gateway:/app"
      - "node_modules:/app/node_modules"
    command: node app/index.js
    restart: always
  
  service_2:
    image: node:20
    container_name : catalogue_container
    ports:
      - 8001:8001
    restart: always
    env_file:
      - .env.docker.local
    volumes: 
      - "dist/catalog:/app"
      - "node_modules:/app/node_modules"
    command: node app/index.js
  
  service_3:
    image: animes
    container_name : anime_container
    ports:
      - 8002:8002
    restart: always
    env_file:
      - .env.docker.local
    volumes: 
      - "dist/catalog:/app"
      - "node_modules:/app/node_modules"
    command: node app/index.js